# Generated by Django 5.2.1 on 2025-05-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('year', models.IntegerField()),
                ('total_sales', models.FloatField()),
                ('total_sold', models.IntegerField()),
                ('flat_sold', models.IntegerField()),
                ('office_sold', models.IntegerField()),
                ('shop_sold', models.IntegerField()),
                ('others_sold', models.IntegerField()),
                ('flat_avg_price', models.FloatField()),
                ('office_avg_price', models.FloatField()),
                ('shop_avg_price', models.FloatField()),
                ('others_avg_price', models.FloatField()),
                ('total_units', models.IntegerField()),
                ('total_area', models.FloatField()),
            ],
            options={
                'unique_together': {('location', 'year')},
            },
        ),
    ]
